# Generated by Django 4.2 on 2023-05-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='coin',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
