# Generated by Django 4.2 on 2023-05-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_pharmacist_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
