# Generated by Django 4.2 on 2023-06-01 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient', models.CharField(blank=True, max_length=250, null=True)),
                ('drug_history', models.TextField(blank=True, null=True)),
                ('main_diagnosis', models.TextField(blank=True, null=True)),
                ('intervention_prescription', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.pharmacist')),
            ],
        ),
    ]
