# Generated by Django 4.2 on 2023-06-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_paymenthistory_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
    ]
