# Generated by Django 4.2 on 2023-06-30 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('upload_prescription', models.FileField(blank=True, null=True, upload_to='upload/prescription')),
                ('recipent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('recipent_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recipent_address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(blank=True, max_length=250, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=250, null=True)),
                ('dosage_form', models.CharField(blank=True, choices=[('TABLET', 'TABLET'), ('CAPSULE', 'CAPSULE'), ('SYRUP', 'SYRUP'), ('SOLUTION', 'SOLUTION'), ('EMULSION', 'EMULSION'), ('SUSPENSION', 'SUSPENSION'), ('INHALER', 'INHALER'), ('CREAM', 'CREAM'), ('PASTE', 'PASTE'), ('GEL', 'GEL')], default='TABLET', max_length=20, null=True)),
                ('dose_strength', models.CharField(blank=True, max_length=150, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_details', to='medications.medication')),
            ],
        ),
    ]
