# Generated by Django 4.2 on 2023-06-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='dosage_form',
            field=models.CharField(blank=True, choices=[('TABLET', 'TABLET'), ('CAPSULE', 'CAPSULE'), ('SYRUP', 'SYRUP'), ('SOLUTION', 'SOLUTION'), ('EMULSION', 'EMULSION'), ('SUSPENSION', 'SUSPENSION'), ('INHALER', 'INHALER'), ('CREAM', 'CREAM'), ('PASTE', 'PASTE'), ('GEL', 'GEL')], default='TAB', max_length=20, null=True),
        ),
    ]
