# Generated by Django 4.2 on 2023-07-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_medication_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='medication_details',
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_details',
            field=models.ManyToManyField(related_name='medications', to='medications.medicationdetail'),
        ),
    ]
