# Generated by Django 4.2 on 2023-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medication_city_medication_recipent_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(blank=True, max_length=250, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=250, null=True)),
                ('dosage_form', models.CharField(blank=True, choices=[('TABLET', 'TABLET'), ('CAPSULE', 'CAPSULE'), ('SYRUP', 'SYRUP'), ('SOLUTION', 'SOLUTION'), ('EMULSION', 'EMULSION'), ('SUSPENSION', 'SUSPENSION'), ('INHALER', 'INHALER'), ('CREAM', 'CREAM'), ('PASTE', 'PASTE'), ('GEL', 'GEL')], default='TABLET', max_length=20, null=True)),
                ('dose_strength', models.CharField(blank=True, max_length=150, null=True)),
                ('extra_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='medication',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dosage_form',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dose_strength',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='generic_name',
        ),
        migrations.AddField(
            model_name='medication',
            name='medication_details',
            field=models.JSONField(default=list),
        ),
    ]
