# Generated by Django 4.2 on 2023-06-30 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medications', '0004_medicationdetail_remove_medication_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
