# Generated by Django 4.2 on 2023-06-26 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_alter_medicalrecord_height_and_more'),
        ('chat', '0002_rename_created_at_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='allergy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.patientallergy'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='fam_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.familyhistory'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='med_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.medicalhistory'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='med_records',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biodata.medicalrecord'),
        ),
    ]
