# Generated by Django 4.2 on 2023-06-20 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_customuser_phone_number'),
        ('chat', '0002_chatroom_end_time_message_sender_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='accounts.client'),
        ),
    ]
