# Generated by Django 4.2 on 2023-06-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chatroom_allergy_alter_chatroom_fam_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
