# Generated by Django 4.2 on 2023-06-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='name',
            new_name='allergy_name',
        ),
    ]
