# Generated by Django 4.2 on 2023-07-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyhistory',
            old_name='risk',
            new_name='risks',
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='history',
            new_name='histories',
        ),
        migrations.RenameField(
            model_name='patientallergy',
            old_name='allergy',
            new_name='allergies',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='is_toggled',
        ),
        migrations.RemoveField(
            model_name='history',
            name='is_toggled',
        ),
        migrations.RemoveField(
            model_name='riskfactor',
            name='is_toggled',
        ),
    ]
