# Generated by Django 4.2 on 2023-06-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_rename_name_allergy_allergy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyhistory',
            name='risk',
            field=models.ManyToManyField(to='biodata.riskfactor'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='history',
            field=models.ManyToManyField(to='biodata.history'),
        ),
        migrations.AlterField(
            model_name='patientallergy',
            name='allergy',
            field=models.ManyToManyField(to='biodata.allergy'),
        ),
    ]
