# Generated by Django 4.2 on 2023-06-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0003_alter_familyhistory_risk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergy',
            old_name='allergy_name',
            new_name='name',
        ),
    ]
