# Generated by Django 4.2 on 2023-06-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0005_alter_medicalrecord_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='height',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
