# Generated by Django 4.2 on 2023-07-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
        migrations.AlterField(
            model_name='pharmacist',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='upload/profile'),
        ),
    ]
