# Generated by Django 4.2 on 2023-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_pharmacist_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='upload/client profile'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='upload/pharma profile'),
        ),
    ]
