# Generated by Django 4.2 on 2023-05-17 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
        ('biodata', '0002_alter_medicalrecord_height'),
        ('chat', '0001_initial'),
        ('accounts', '0002_remove_plan_coin_value_plan_coin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientProfile',
            new_name='Client',
        ),
        migrations.RenameModel(
            old_name='PharmacistProfile',
            new_name='Pharmacist',
        ),
    ]
