# Generated by Django 4.2 on 2023-05-18 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_code',
        ),
    ]
