# Generated by Django 4.2 on 2023-05-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customuser_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=12, null=True),
        ),
    ]
