# Generated by Django 4.2 on 2023-05-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_pharmacist_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacist',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
