# Generated by Django 4.2 on 2023-06-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_careform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='coin',
        ),
    ]
