# Generated by Django 4.2 on 2023-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_paymenthistory_options_paymenthistory_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paystack_access_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paystack_charge_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
