# Generated by Django 4.2 on 2023-05-15 15:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('generic_name', models.CharField(blank=True, max_length=250, null=True)),
                ('brand_name', models.CharField(blank=True, max_length=250, null=True)),
                ('dosage_form', models.CharField(blank=True, choices=[('TAB', 'TAB'), ('CAP', 'CAP'), ('SYR', 'SYR'), ('SOL', 'SOL'), ('EMU', 'EMU'), ('SUS', 'SUS'), ('INH', 'INH'), ('CRE', 'CRE'), ('PAS', 'PAS'), ('GE:', 'GEL')], default='TAB', max_length=20, null=True)),
                ('dose_strength', models.CharField(blank=True, max_length=150, null=True)),
                ('upload_prescription', models.FileField(blank=True, null=True, upload_to='upload/prescription')),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recipent_name', models.CharField(blank=True, max_length=150, null=True)),
                ('recipent_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recipent_address', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PEN', 'PEN'), ('DEL', 'DEL')], default='PEN', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medications.medication')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.clientprofile')),
            ],
        ),
    ]
