# Generated by Django 4.2 on 2023-05-11 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='accounts.clientprofile'),
        ),
    ]
